# Multiple Regression

In [11]:
#Load your packages
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import pandas as pa
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm


%matplotlib inline

In [2]:
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

# Time For Data 

In [3]:
data = pa.read_csv('bikes.csv') #this is the file from exam 1

In [4]:
data

Bike       Date  Distance     Time  Minutes  AvgSpeed  TopSpeed  \
0    Steel   20/01/10    27.200  1:55:04   115.07     14.10     31.50   
1   Carbon   21/01/10    27.460  1:55:35   115.58     14.25     30.64   
2    Steel   25/01/10    27.200  1:55:45   115.75     14.10     30.92   
3   Carbon   26/01/10    27.520  1:53:56   113.93     14.49     33.02   
4   Carbon   27/01/10    27.510  1:59:12   119.20     13.84     30.92   
5    Steel   1/2/2010    27.170  1:48:44   108.73     14.99     32.09   
6    Steel   3/2/2010    27.160  1:57:44   117.73     13.84     32.09   
7   Carbon   3/2/2010    27.490  2:03:20   123.33     13.37     29.58   
8   Carbon   8/2/2010    27.480  1:52:30   112.50     14.65     34.02   
9    Steel   9/2/2010    27.090  1:52:37   112.62     14.43     32.71   
10  Carbon  11/2/2010    27.440  1:57:41   117.68     13.99     32.00   
11  Carbon   1/3/2010    27.490  1:48:38   108.63     15.18     32.71   
12  Carbon   3/3/2010    27.490  1:50:53   110.88     14.82     34.71   
13   Steel   4/3/2010    27.160  1:49:34   109.57     14.87     33.50   
14   Steel   8/3/2010    27.400  1:53:04   113.07     14.56     32.40   
15  Carbon  10/3/2010    27.266  1:45:52   105.87     15.45     32.09   
16  Carbon  12/3/2010    27.290  1:52:35   112.58     14.54     33.02   
17  Carbon   15/03/10    27.330  1:52:26   112.43     14.58     34.10   
18   Steel   17/03/10    27.000  1:43:58   103.97     15.58     33.08   
19   Steel   22/03/10    27.060  1:52:52   112.87     14.32     32.71   
20   Steel   23/03/10    26.990  1:44:45   104.75     15.46     35.10   
21   Steel   25/03/10    25.860  1:45:28   105.47     14.71     34.71   
22  Carbon   29/03/10    27.360  1:49:35   109.58     14.98     32.09   
23   Steel   30/03/10    27.010  1:51:02   111.03     14.59     32.40   
24   Steel   1/4/2010    27.030  1:51:19   111.32     14.57     32.40   
25   Steel  12/4/2010    27.100  1:45:25   105.42     15.32     36.00   
26   Steel   14/04/10    27.000  1:50:12   110.20     14.69     35.10   
27   Steel   19/04/10    27.050  1:48:42   108.70     14.92     33.35   
28  Carbon   21/04/10    27.340  1:42:36   102.60     15.99     34.84   
29  Carbon   26/04/10    27.310  1:43:49   103.82     15.78     33.02   
30  Carbon   28/04/10    27.320  1:42:45   102.75     15.95     34.00   
31   Steel   29/04/10    26.950  1:41:43   101.72     15.90     34.71   
32  Carbon   4/5/2010    27.400  1:41:51   101.85     16.15     35.02   
33   Steel  10/5/2010    26.940  1:37:40    97.67     16.55     35.66   
34  Carbon  11/5/2010    27.340  1:47:14   107.23     15.10     32.71   
35   Steel  12/5/2010    27.020  1:48:15   108.25     14.98     32.40   
36   Steel   13/05/10    26.940  1:43:15   103.25     15.66     33.68   
37  Carbon   28/05/10    27.310  1:40:05   100.08     16.25     35.00   
38   Steel  10/6/2010    27.030  1:51:56   111.93     14.48     34.02   
39   Steel   14/06/10    27.020  1:42:26   102.43     15.83     34.02   
40   Steel   15/06/10    26.920  1:40:36   100.60     16.05     36.00   
41   Steel   21/06/10    26.900  1:46:28   106.47     15.16     33.80   
42  Carbon   22/06/10    27.320  1:40:41   100.68     16.28     36.00   
43   Steel   23/06/10    26.910  1:41:35   101.58     15.89     33.34   
44   Steel   25/06/10    26.940  1:50:29   110.48     14.63     32.40   
45  Carbon   5/7/2010    27.360  1:41:35   101.58     16.15     34.00   
46  Carbon   6/7/2010    27.390  1:45:03   105.05     15.64     35.02   
47  Carbon   7/7/2010    27.380  1:42:54   102.90     15.96     33.35   
48   Steel   8/7/2010    26.910  1:45:57   105.95     15.24     34.40   
49  Carbon  12/7/2010    26.740  1:41:52   101.87     15.75     35.02   
50   Steel   13/07/10    26.600  1:46:50   106.83     14.94     33.68   
51  Carbon   15/07/10    27.430  1:50:36   110.60     14.86     33.02   
52  Carbon   19/07/10    27.450  1:45:31   105.52     15.61     35.66   
53   Steel   20/07/10    26.910  1:45:36   105.60     15.28     

In [5]:
#Let's try to predict the time of the ride based on the speeds
#I need the data in numpy arrays rather than panda data frames.  This is what I do here
X = np.array(data.iloc[:,5:7])
y = np.array(data.iloc[:,4])

In [6]:
X #no more leading indexes...

array([[ 14.1 ,  31.5 ],
       [ 14.25,  30.64],
       [ 14.1 ,  30.92],
       [ 14.49,  33.02],
       [ 13.84,  30.92],
       [ 14.99,  32.09],
       [ 13.84,  32.09],
       [ 13.37,  29.58],
       [ 14.65,  34.02],
       [ 14.43,  32.71],
       [ 13.99,  32.  ],
       [ 15.18,  32.71],
       [ 14.82,  34.71],
       [ 14.87,  33.5 ],
       [ 14.56,  32.4 ],
       [ 15.45,  32.09],
       [ 14.54,  33.02],
       [ 14.58,  34.1 ],
       [ 15.58,  33.08],
       [ 14.32,  32.71],
       [ 15.46,  35.1 ],
       [ 14.71,  34.71],
       [ 14.98,  32.09],
       [ 14.59,  32.4 ],
       [ 14.57,  32.4 ],
       [ 15.32,  36.  ],
       [ 14.69,  35.1 ],
       [ 14.92,  33.35],
       [ 15.99,  34.84],
       [ 15.78,  33.02],
       [ 15.95,  34.  ],
       [ 15.9 ,  34.71],
       [ 16.15,  35.02],
       [ 16.55,  35.66],
       [ 15.1 ,  32.71],
       [ 14.98,  32.4 ],
       [ 15.66,  33.68],
       [ 16.25,  35.  ],
       [ 14.48,  34.02],
       [ 15.83,  34.02],


In [7]:
#sklearn is a really amazing package! But is a little tricky to code.  You should first define the regressor
linreg = LinearRegression()#define it as a regular linear regression
linreg.fit(X,y)#This fits it!
linreg.score(X,y)#This is the R^2 value

0.95229289437369646

In [8]:
#You can make predictions
somevalues = [[13,35]]
linreg.predict(somevalues)

array([ 121.95051259])

In [9]:
#you can get the coefficients
linreg.coef_

array([-6.8576774 , -0.37102638])

In [10]:
#and the intercept
linreg.intercept_

224.08624193729182

In [11]:
#I can now do crazier features
X = np.append(X,X**2,axis = 1) #Here I square each value and gle that onto the end of X


In [12]:
X = np.insert(X,-1,[X[:,0]*X[:,1]],axis = 1) #Here i multiply the first two values and glue that ontu the end of X.

In [13]:
X

array([[   14.1   ,    31.5   ,   198.81  ,   444.15  ,   992.25  ],
       [   14.25  ,    30.64  ,   203.0625,   436.62  ,   938.8096],
       [   14.1   ,    30.92  ,   198.81  ,   435.972 ,   956.0464],
       [   14.49  ,    33.02  ,   209.9601,   478.4598,  1090.3204],
       [   13.84  ,    30.92  ,   191.5456,   427.9328,   956.0464],
       [   14.99  ,    32.09  ,   224.7001,   481.0291,  1029.7681],
       [   13.84  ,    32.09  ,   191.5456,   444.1256,  1029.7681],
       [   13.37  ,    29.58  ,   178.7569,   395.4846,   874.9764],
       [   14.65  ,    34.02  ,   214.6225,   498.393 ,  1157.3604],
       [   14.43  ,    32.71  ,   208.2249,   472.0053,  1069.9441],
       [   13.99  ,    32.    ,   195.7201,   447.68  ,  1024.    ],
       [   15.18  ,    32.71  ,   230.4324,   496.5378,  1069.9441],
       [   14.82  ,    34.71  ,   219.6324,   514.4022,  1204.7841],
       [   14.87  ,    33.5   ,   221.1169,   498.145 ,  1122.25  ],
       [   14.56  ,    32.4   ,   

In [14]:
linreg.fit(X,y)#Linear Regress again!
linreg.score(X,y)

0.96085224359758858

In [15]:
linreg.coef_

array([ -2.70841485e+01,  -4.47437844e+00,   6.70439176e-01,
        -2.16276289e-03,   6.32428750e-02])

In [16]:
linreg.intercept_

443.73630413445812

# How About Another Package?

In [18]:
model = sm.OLS(y, X).fit()
predictions = model.predict(X) # make the predictions by the model

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 5.626e+04
Date:                Tue, 19 Feb 2019   Prob (F-statistic):           4.02e-94
Time:                        13:27:11   Log-Likelihood:                -100.52
No. Observations:                  56   AIC:                             211.0
Df Residuals:                      51   BIC:                             221.2
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -2.6485     13.535     -0.196      0.846     -29.822      24.525
x2            11.1733      6.104      1.830      0.073      -1.082      23.428
x3            -0.5861      0.799     -0.734      0.466      -2.189       1.017
x4             0.3999      0.605      0.661      0.512      -0.815       1.615
x5            -0.2622      0.164     -1.598      0.116      -0.592       0.067
==============================================================================
Omnibus:                        4.690   Durbin-Watson:                   1.865
Prob(Omnibus):                  0.096   Jarque-Bera (JB):                5.558
Skew:                          -0.124   Prob(JB):                       0.0621
Kurtosis:                       4.523   Cond. No.                     9.20e+04
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 9.2e+04. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [19]:
residuals = 0

for i in range (0,len(y)):
    residuals = residuals + (y[i]-predictions[i])**2

In [20]:
residuals

118.80472447309529

Woof!  They do not agree!  Does not give an intercept though!  So add a column of 1s to the array.

In [26]:
X1 = np.insert(X,0,np.ones(len(X[:,0])),axis = 1)

In [27]:
model = sm.OLS(y, X1).fit()
predictions = model.predict(X1) # make the predictions by the model

# Print out the statistics
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.961
Model:                            OLS   Adj. R-squared:                  0.957
Method:                 Least Squares   F-statistic:                     245.4
Date:                Tue, 19 Feb 2019   Prob (F-statistic):           6.28e-34
Time:                        13:37:54   Log-Likelihood:                -83.707
No. Observations:                  56   AIC:                             179.4
Df Residuals:                      50   BIC:                             191.6
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        443.7363     69.175      6.415      0.000     304.795     582.678
x1           -27.0841     10.817     -2.504      0.016     -48.812      -5.357
x2            -4.4744      5.177     -0.864      0.392     -14.872       5.924
x3             0.6704      0.629      1.066      0.291      -0.592       1.933
x4            -0.0022      0.457     -0.005      0.996      -0.920       0.916
x5             0.0632      0.133      0.476      0.636      -0.204       0.330
==============================================================================
Omnibus:                       24.257   Durbin-Watson:                   1.787
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               61.243
Skew:                          -1.180   Prob(JB):                     5.03e-14
Kurtosis:                       7.548   Cond. No.                     5.74e+05
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.74e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [12]:
data = [5,-5,-3,10,6,5,13,-1]

In [13]:
np.mean(data)

3.75

In [14]:
15/4

3.75

In [16]:
np.std(data,ddof = 1)

6.2962573917254323

In [18]:
np.sqrt((390-8*3.75**2)/7)

6.2962573917254323

In [19]:
t = (3.75-3)/(np.std(data,ddof = 1)/np.sqrt(8))

In [20]:
t

0.33691766577832261

In [27]:
2*stats.t.cdf(-1.059,54)

0.29431392691674085