# Two Way Anova

In [1]:
#Load your packages
import numpy as np
from scipy import stats
import matplotlib.pyplot as plt
import pandas as pa



%matplotlib inline

In [2]:
#https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html

# Time For Data 

In [3]:
data = pa.read_csv('student.csv') #We used this data for contingency tables.

In [4]:
data.iloc[0:20,:]

Year Gender Smoke    Award HigherSAT  Exercise    TV  Height  Weight  \
0      Senior      M    No  Olympic      Math      10.0   1.0    71.0   180.0   
1   Sophomore      F   Yes  Academy      Math       4.0   7.0    66.0   120.0   
2   FirstYear      M    No    Nobel      Math      14.0   5.0    72.0   208.0   
3      Junior      M    No    Nobel      Math       3.0   1.0    63.0   110.0   
4   Sophomore      F    No    Nobel    Verbal       3.0   3.0    65.0   150.0   
5   Sophomore      F    No    Nobel    Verbal       5.0   4.0    65.0   114.0   
6   FirstYear      F    No  Olympic      Math      10.0  10.0    66.0   128.0   
7   Sophomore      M    No  Olympic      Math      13.0   8.0    74.0   235.0   
8      Junior      F    No    Nobel    Verbal       3.0   6.0    61.0     NaN   
9   FirstYear      F    No    Nobel      Math      12.0   1.0    60.0   115.0   
10  Sophomore      F    No  Olympic      Math      12.0   6.0    65.0   140.0   
11  FirstYear      M    No  Olympic      Math      10.0   5.0    63.0   200.0   
12  Sophomore      M    No  Olympic      Math      12.0   8.0    68.0   162.0   
13     Junior      F    No    Nobel    Verbal       6.0   1.0    68.0   135.0   
14  FirstYear      M    No    Nobel    Verbal       9.0   5.0    68.0   193.0   
15  FirstYear      F    No  Olympic      Math      10.0   2.0    63.0   110.0   
16  FirstYear      F    No  Olympic    Verbal       3.0  15.0    63.0    99.0   
17  Sophomore      M    No    Nobel    Verbal       7.0   3.0    72.0   165.0   
18  Sophomore      F    No    Nobel      Math       2.0   1.0    62.0   120.0   
19  Sophomore      F    No  Olympic    Verbal      14.0   2.0    67.0   154.0   

    Siblings  BirthOrder  VerbalSAT  MathSAT   SAT   GPA  Pulse  Piercings  
0          4         4.0        540      670  1210  3.13     54        0.0  
1          2         2.0        520      630  1150  2.50     66        3.0  
2          2         1.0        550      560  1110  2.55    130        0.0  
3          1         1.0        490      630  1120  3.10     78        0.0  
4          1         1.0        720      450  1170  2.70     40        6.0  
5          2         2.0        600      550  1150  3.20     80        4.0  
6          1         1.0        640      680  1320  2.77     94        8.0  
7          1         1.0        660      710  1370  3.30     77        0.0  
8          2         2.0        550      550  1100  2.80     60        7.0  
9          7         8.0        670      700  1370  3.70     94        2.0  
10         1         2.0        500      670  1170  2.09     63        2.0  
11         2         2.0        580      600  1180   NaN     72        0.0  
12         3         NaN        530      620  1150  2.90     54        0.0  
13         2         3.0        650      650  1300  3.08     66        4.0  
14         1         1.0        700      650  1350   NaN     72        0.0  
15         1         2.0        590      610  1200  3.86     59        4.0  
16         2         1.0        600      600  1200  3.00     88        4.0  
17         2         1.0        700      650  1350  3.00     59        0.0  
18         1         1.0        610      800  1410  3.35     64        2.0  
19         1         2.0        550      450  1000  3.30     72        5.0

In [5]:
#I am going to look at men vs woman, smoking and the effects on height.
smoke = np.array(data.iloc[:,2])
gender = np.array(data.iloc[:,1])
height = np.array(data.iloc[:,7])

In [6]:
#bianize the data...
smoker = smoke == 'Yes'
male = gender == 'M'

In [7]:
ms = height[smoker*male]#grabing male smokers
ms = ms[~np.isnan(ms)] #getting rid of missing data
nms = len(ms) #computing the length
ms = ms[np.random.choice(len(ms),10)] #randomly choicing 10 from the data
mums = np.mean(ms) #compute the mean
ws = height[smoker*np.logical_not(male)] #Do it again...
ws = ws[~np.isnan(ws)]
nws = len(ws)
ws = ws[np.random.choice(len(ws),10)]
muws = np.mean(ws)
mn = height[np.logical_not(smoker)*male]
mn = mn[~np.isnan(mn)]
nmn = len(mn)
mn = mn[np.random.choice(len(mn),10)]
mumn = np.mean(mn)
wn = height[np.logical_not(smoker)*np.logical_not(male)]
wn = wn[~np.isnan(wn)]
nwn = len(wn)
wn = wn[np.random.choice(len(wn),10)]
muwn = np.mean(wn)

In [8]:
ms

array([ 72.,  69.,  74.,  73.,  67.,  75.,  74.,  73.,  68.,  70.])

In [9]:
mn

array([ 71.,  72.,  71.,  66.,  72.,  70.,  68.,  76.,  71.,  66.])

In [10]:
ws

array([ 64.,  60.,  66.,  65.,  67.,  66.,  66.,  66.,  66.,  66.])

In [11]:
wn

array([ 68.,  67.,  66.,  63.,  66.,  65.,  64.,  63.,  64.,  66.])

Time for some sum of the squares computations

In [12]:
w = np.append(ws,wn) #Make woman
nw = len(w)
muw = np.mean(w)
m = np.append(ms,mn)#make men
nm = len(m)
mum = np.mean(m)
s = np.append(ms,ws)#smokers
nums = len(s)
mus = np.mean(s)
ns = np.append(mn,wn)#not
nns = len(ns)
muns = np.mean(ns)

In [13]:
heightnew = np.append(w,m) #make all 
mean = np.mean(heightnew)
print(len(heightnew))
mean

40


67.974999999999994

In [14]:
#so now we compute!
SStot = 40*np.std(heightnew)**2
SSgen = 2*10*((mean-muw)**2+(mean-mum)**2)
SSsmo = 2*10*((mean-mus)**2+(mean-muns)**2)
SSbetw = 10*((mums-mum-mus+mean)**2+(muws-muw-mus+mean)**2+(mumn-mum-muns+mean)**2+(muwn-muw-muns+mean)**2)
SSe = SStot-SSgen-SSsmo - SSbetw 

In [15]:
SSe

242.90000000000032

In [16]:
Fint = (SSbetw/1)/(SSe/(40-4))
Fgen = SSgen/(SSe/(40-4))
Fsmo = SSsmo/(SSe/(40-4))
Famoung = ((SSgen+SSsmo+SSbetw)/3)/(SSe/(40-4))

In [18]:
#Great let's get some p values and move on with our lives...
print(1-stats.f.cdf(Fint,1,36))
print(1-stats.f.cdf(Fgen,1,36))
print(1-stats.f.cdf(Fsmo,1,36))
print(1-stats.f.cdf(Famoung,3,36))

0.58718599466
6.86196313104e-08
0.58718599466
1.29833305129e-06


In [136]:
print(mum,muw)

70.9 65.9


In [138]:
print(mus,muns)

69.8 67.0


In [22]:
SSe

242.90000000000032

This was not the most effiecient code but it should give you an idea of what it takes to do the two way ANOVA.  Be aware of the sampling I had to do on the data set to get the data ranges to match up!